name: MacPulse - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyze MacPulse project
    runs-on: macos-14
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Xcode Version to 16.2
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app
          xcodebuild -version

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Build and Analyze MacPulse-macOS
        run: |
          xcodebuild clean build analyze \
            -project MacPulse.xcodeproj \
            -scheme MacPulse-macOS \
            -destination 'platform=macOS,arch=arm64,name=My Mac' \
            | xcpretty

      - name: Build and Analyze MacPulse-Monitor
        run: |
          xcodebuild clean build analyze \
            -project MacPulse.xcodeproj \
            -scheme MacPulse-Monitor \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            | xcpretty
